name: Package Publish CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v2
    - name: Set Run ID
      run: |
        echo ::set-env name=BOT_USERNAME::${{ secrets.BOT_TOKEN }}
        echo ::set-env name=BOT_TOKEN::${{ secrets.BOT_USERNAME }}
        echo ::set-env name=GITHUB_RUN_ID::${{ github.run_id }}

      
    - name: Assemble the aar file
      run: ./gradlew assemble

    - name: Publish Package
      run: ./gradlew publish
    
    - name: Read Properties
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './version.properties'
        property: 'version'
    - name: Print Version
      run: echo ${{ steps.read_property.outputs.value }}

    - name: Tag Release
      run: |
        git config --local user.email bot@pactsafe.com
        git config --local user.name "PactSafe Publish Action"
        git tag ${{ steps.read_property.outputs.value }}
        git push --tags

    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.read_property.outputs.value }}
        release_name: Release ${{ steps.read_property.outputs.value }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: falsel
    
    - name: Increment Version Revision
      run: ./gradlew incrementRevision
      
    - name: Commit changes
      run: git commit -am "[skip ci] version revision bump"
        
    - name: Push Changes
      run: git push
